### PR TITLE
Add more country flags

### PR DESCRIPTION
**Pull request by Brueggus**
I've added (hopefully) all missing country flags from twemoji to the extension.

Few remarks:
* The entries are sorted by their alpha-2 code in the source code
* I've kept the existing two-letter-emojis (`['jp', 'kr', 'cn', 'us', 'ru', 'gb']`)
* For all new records, the country's name is used (`:croatia:`) as reference as long as it contains less than three words. Otherwise the alpha-2 code (`:tf: for "French Southern Territories"`) is used

Let me know what you think!

### CODE REVIEW

**Comment by markseuffert** [comment]
Hi Alexander, thank you for the pull request and taking the time to contribute code.

I think there are too many twemoji icons to include them all. When I designed this extension, I decided to use only the most popular icons and split them into stacks. This way the web browser never has to load too many resources at once and the loading time never gets too long. The script that I used to make the SVG stacks, made files that were 128 KB or less in size, which is about the size of a typical image. Perhaps you see the dilemma. How about adding a few more flags? Is there a particular flag that you need?

**Comment by Brueggus** [comment]
Hi Mark,
> Perhaps you see the dilemma. 
Yes, I've noticed that the svg file has grown quite a bit and I agree that this has a negative impact on loading times.

I've noticed that some countries in the APAC region were missing (Singapore, Australia, New Zealand) but also Moldova or Chile, for example. It would be pretty difficult to decide which ones to add and which not... :/

**Comment by markseuffert** [comment]
Yes, this would be difficult. At the moment the emoji extension contains a subset of all emojis. Even if we would add a few more flags to the extension, the concept of most popular icons just doesn't work when it comes to flags. Perhaps it's better to break this up into two problems? I suggest to make a new "flag" extension that contains all flags and we keep this a "basic emoji" extension?

**Comment by Brueggus** [comment]
> I suggest to make a new "flag" extension that contains all flags and we keep this a "basic emoji" extension?

This would create two extensions with different names but lots of similar code which needs to be maintained. Both extensions basically do the same. And this would break compatibility for those who currently use the Emoji extension to display flags.

We could keep everything as-is, add the new flags and split the flags into multiple stacks of <=128KB (just like the "normal" emojis) to reduce the amount of data that clients need to transfer.

The option I like most but which likely requires a lot of code changes would be to make the Emoji extension customizeable, i. e. one could upload SVG files to a directory on the web server and use them as emojis in addition to the default set. This would allow any custom emoji, not just flags. But I doubt that the current concept of using a CSS class per emoji would still work in that case.

**Comment by markseuffert** [comment]
Good points. We have three alternatives at the moment. Make a new flag extension, extend the emoji extension with more stacks, create an emoji construction kit. You could argue that all three alternatives would fit into our minimalistic design philosophy. I suggest to discuss this with our community. See also https://github.com/datenstrom/yellow/discussions/757.

**Pull request closed without merging**
